# Generated by Django 4.0 on 2022-01-02 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat2', '0002_auto_20210329_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='django_private_chat2.messagemodel', verbose_name='Reply to'),
        ),
    ]
