# Generated by Django 3.1.7 on 2021-03-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat2', '0002_auto_20210312_1204'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dialogsmodel',
            name='Unique dialog',
        ),
        migrations.AddConstraint(
            model_name='dialogsmodel',
            constraint=models.UniqueConstraint(fields=(('user1', 'user2'), ('user2', 'user1')), name='Unique dialog'),
        ),
    ]
