# Generated by Django 3.1.7 on 2021-03-23 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_private_chat2', '0002_auto_20210312_1204'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dialogsmodel',
            name='Unique dialog',
        ),
        migrations.AlterUniqueTogether(
            name='dialogsmodel',
            unique_together={('user2', 'user1'), ('user1', 'user2')},
        ),
    ]
